/**
 * Course Service.
 *
 * Manages database operations for Courses, Modules, and Lessons.
 * Provides clean error recovery via transactional cleanup (delete cascade).
 */

import { supabase, unwrap } from "../config/supabase.js"
import { env } from "../config/env.js"
import { enqueueJob } from "./jobQueue.js"

export class CourseService {
  /**
   * Creates a course, its modules, and its lessons atomically in the database.
   * If any insert fails, it deletes the parent course record, which cascadingly
   * cleans up all child modules and lessons.
   *
   * @param {object} params
   * @param {object} params.structure     Course structure generated by the agent.
   * @param {string} params.userId        Owner student user UUID.
   * @param {string} params.skillId       Target skill UUID.
   * @param {string} [params.taskId]      Optional parent learning task UUID.
   * @returns {Promise<{ courseId: string, lessonIds: string[] }>}
   */
  async createCourseFromStructure({ structure, userId, skillId, taskId = null }) {
    let createdCourseId = null

    try {
      // 1. Create the parent course record.
      const course = unwrap(
        await supabase
          .from("courses")
          .insert({
            title: structure.title,
            description: structure.description,
            skill_id: skillId,
            user_id: userId,
            task_id: taskId,
            difficulty_level: structure.difficulty || "intermediate",
            estimated_duration_hours: structure.estimatedHours || 10,
            generated_by_ai: true,
            ai_model_used: env.ai.provider,
            status: "draft", // Start as draft, publish after content population
          })
          .select("id")
          .single(),
        "Inserting course parent record",
      )

      createdCourseId = course.id
      const lessonIds = []

      // 2. Insert modules and lessons.
      const modules = structure.modules || []
      for (let modIdx = 0; modIdx < modules.length; modIdx++) {
        const modData = modules[modIdx]

        const moduleRecord = unwrap(
          await supabase
            .from("course_modules")
            .insert({
              course_id: createdCourseId,
              module_number: modIdx + 1,
              title: modData.title,
              objective: modData.objective,
              estimated_duration_hours: modData.estimatedHours || 2,
              mastery_threshold: 80,
            })
            .select("id")
            .single(),
          `Inserting course module ${modIdx + 1}`,
        )

        const lessons = modData.lessons || []
        for (let lesIdx = 0; lesIdx < lessons.length; lesIdx++) {
          const lesData = lessons[lesIdx]

          const lessonRecord = unwrap(
            await supabase
              .from("lessons")
              .insert({
                module_id: moduleRecord.id,
                lesson_number: lesIdx + 1,
                title: lesData.title,
                description: lesData.description,
                learning_objective: lesData.objective || lesData.description,
                key_concepts: lesData.keyConcepts || [],
                content_markdown: null, // "content_pending" state
                estimated_duration_minutes: lesData.estimatedMinutes || 45,
              })
              .select("id")
              .single(),
            `Inserting lesson ${lesIdx + 1} of module ${modIdx + 1}`,
          )

          lessonIds.push(lessonRecord.id)
        }
      }

      // 3. Enqueue content population job using the general job queue.
      // This schedules the async content generation (videos, summaries, quizzes).
      await enqueueJob({
        type: "course.populate_content",
        userId,
        payload: {
          courseId: createdCourseId,
          lessonIds,
        },
      })

      return {
        courseId: createdCourseId,
        lessonIds,
      }
    } catch (error) {
      console.error("[CourseService] Transaction failed. Cleaning up...", error.message)

      // Cascading cleanup of partial data.
      if (createdCourseId) {
        try {
          await supabase.from("courses").delete().eq("id", createdCourseId)
          console.log(`[CourseService] Cleaned up course ${createdCourseId} successfully.`)
        } catch (cleanupError) {
          console.error("[CourseService] Failed to clean up partial course:", cleanupError.message)
        }
      }

      throw error
    }
  }

  /**
   * Publishes the course, changing status from 'draft' to 'generated'.
   *
   * @param {string} courseId
   */
  async publishCourse(courseId) {
    unwrap(
      await supabase
        .from("courses")
        .update({ status: "generated" })
        .eq("id", courseId)
        .select("id")
        .single(),
      "Publishing course",
    )
  }
}

export const courseService = new CourseService()
export default courseService
